module.exports = {
  PORT: process.env.PORT || 3000,

  DB_FILE: "chat.db",
  UPLOAD_DIR: "uploads",

  MAX_MESSAGE_LENGTH: 500,
  MAX_NAME_LENGTH: 20,
  MAX_ROOM_NAME_LENGTH: 30,
  MAX_CODE_LENGTH: 20,
  MIN_CODE_LENGTH: 3,
  GENERATED_CODE_LENGTH: 6,

  MIN_PASSWORD_LENGTH: 4,
  MAX_PASSWORD_LENGTH: 64,

  MAX_FILE_BYTES: 10 * 1024 * 1024,

  HISTORY_LIMIT: 50,
  MIN_MS_BETWEEN_MESSAGES: 250,
};
